spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=user1;encrypt=false
    username: huy
    password: 271005
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: huyhoang271005@gmail.com
    password: uqxm ajrv ffom tupe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    show-sql: true
jwt:
  expiration:
    access-token-seconds: 300       #5 min
    refresh-token-seconds: 604800   #7 day
cloudinary:
  cloud-name: ddbcvzxzq
  api-key: 784394426995282
  api-secret: FMKNG113EZDQDPrN_bLirgOQtfg
vnpay:
  tmnCode: VA19C43H
  hashSecret: 6SODDKK52LN07PNR78P5MAMPTM37H98G
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://uncoagulative-tyrannisingly-eddie.ngrok-free.dev/auth/payment-return/vnpay
server:
  port: 8080